@extends('layouts.master')

@section('title', 'Items')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- CSS Links -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.bootstrap5.min.css">

<div class="app-content">
    <div class="container-fluid py-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h2 class="fw-bold">Item List</h2>
            @include('items.create')
        </div>

        <div class="card">
            <div class="card-body">
                <table class="table table-bordered table-striped" id="itemsDataTable" style="width:100%">
                    <thead class="table-dark">
                        <tr>
                            <th>No</th>
                            <th>Item Code</th>
                            <th>Item Name</th>
                            <th>M/F Date</th>
                            <th>Exp Date</th>
                            <th>Company Name</th>
                            <th>Image</th>
                            <th>Quantity</th>
                            <th>Cost Price</th>
                            <th>Selling Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Table body will be generated by Datatables -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript Links -->
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
$(document).ready(function() {
    // Initialize Datatable
    var table = $('#itemsDataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('items.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'item_code', name: 'item_code'},
            {data: 'item_name', name: 'item_name'},
            {data: 'mfd_date', name: 'mfd_date'},
            {data: 'exp_date', name: 'exp_date'},
            {data: 'company_name', name: 'company_name'},
            {data: 'image', name: 'image', orderable: false, searchable: false},
            {data: 'quantity', name: 'quantity'},
            {data: 'cost_price', name: 'cost_price'},
            {data: 'selling_price', name: 'selling_price'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });

    // Delete item functionality - using event delegation for dynamic elements
    $(document).on('click', '.delete-item', function() {
        let itemId = $(this).data('id');

        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '/items/' + itemId,
                    type: 'DELETE',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    success: function(response) {
                        Swal.fire(
                            'Deleted!',
                            'Item has been deleted.',
                            'success'
                        ).then(() => {
                            table.ajax.reload(); // Reload the Datatable
                        });
                    },
                    error: function(xhr) {
                        Swal.fire(
                            'Error!',
                            'Failed to delete item.',
                            'error'
                        );
                    }
                });
            }
        });
    });

    // Edit item functionality - using event delegation
    $(document).on('click', '.edit-item', function() {
        let itemId = $(this).data('id');

        // Fetch item data via AJAX
        $.ajax({
            url: '/items/' + itemId + '/edit',
            type: 'GET',
            success: function(response) {
                // Create a temporary div to hold the response
                let tempDiv = $('<div>').html(response);

                // Find the modal in the response and append it to the body
                let modal = tempDiv.find('#editItemModal');
                $('body').append(modal);

                // Show the modal
                $('#editItemModal').modal('show');

                // Remove the modal when hidden
                $('#editItemModal').on('hidden.bs.modal', function() {
                    $(this).remove();
                });
            },
            error: function(xhr) {
                Swal.fire(
                    'Error!',
                    'Failed to load item data.',
                    'error'
                );
            }
        });
    });

    // Reload the table after modal is closed (assuming your edit form submits via AJAX)
    $(document).on('hidden.bs.modal', '#editItemModal', function() {
        table.ajax.reload(null, false); // Reload without resetting pagination
    });
});
</script>

@endsection
