@extends('layouts.master')

@section('title', 'Items')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- CSS Links -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.bootstrap5.min.css">

<div class="app-content">
    <div class="container-fluid py-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h2 class="fw-bold">Item List</h2>
            <div>
                <button class="btn btn-primary me-2" data-bs-toggle="modal" data-bs-target="#bulkUploadModal">
                    <i class="fas fa-upload me-1"></i> Bulk Upload
                </button>
                @include('items.create')
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <table class="table table-bordered table-striped" id="itemsDataTable" style="width:100%">
                    <thead class="table-dark">
                        <tr>
                            <th>No</th>
                            <th>Item Code</th>
                            <th>Item Name</th>
                            <th>M/F Date</th>
                            <th>Exp Date</th>
                            <th>Supplier</th>
                            <th>Image</th>
                            <th>Quantity</th>
                            <th>Cost Price</th>
                            <th>Selling Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Table body will be generated by Datatables -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Bulk Upload Modal -->
<div class="modal fade" id="bulkUploadModal" tabindex="-1" aria-labelledby="bulkUploadModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bulkUploadModalLabel">Bulk Upload Items</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="bulkUploadForm" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                        <label for="bulkFile" class="form-label">Select Excel/CSV File</label>
                        <input class="form-control" type="file" id="bulkFile" name="file" accept=".xlsx,.xls,.csv" required>
                        <div class="form-text">Please upload an Excel or CSV file with item data.</div>
                    </div>
                    <div class="mb-3">
                        <a href="{{ asset('templates/items_import_template.xlsx') }}" class="btn btn-sm btn-outline-secondary">
                            <i class="fas fa-download me-1"></i> Download Template
                        </a>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="uploadBtn">Upload</button>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript Links -->
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
$(document).ready(function() {
    // Initialize Datatable
    var table = $('#itemsDataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('items.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'item_code', name: 'item_code'},
            {data: 'item_name', name: 'item_name'},
            {data: 'mfd_date', name: 'mfd_date'},
            {data: 'exp_date', name: 'exp_date'},
            {data: 'company_name', name: 'company_name'},
            {data: 'image', name: 'image', orderable: false, searchable: false},
            {data: 'quantity', name: 'quantity'},
            {data: 'cost_price', name: 'cost_price'},
            {data: 'selling_price', name: 'selling_price'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });

    // Delete item functionality
    $(document).on('click', '.delete-item', function() {
        let itemId = $(this).data('id');

        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '/items/' + itemId,
                    type: 'DELETE',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    success: function(response) {
                        Swal.fire(
                            'Deleted!',
                            'Item has been deleted.',
                            'success'
                        ).then(() => {
                            table.ajax.reload();
                        });
                    },
                    error: function(xhr) {
                        Swal.fire(
                            'Error!',
                            'Failed to delete item.',
                            'error'
                        );
                    }
                });
            }
        });
    });

    // Edit item functionality
    $(document).on('click', '.edit-item', function() {
        let itemId = $(this).data('id');

        $.ajax({
            url: '/items/' + itemId + '/edit',
            type: 'GET',
            success: function(response) {
                let tempDiv = $('<div>').html(response);
                let modal = tempDiv.find('#editItemModal');
                $('body').append(modal);
                $('#editItemModal').modal('show');
                $('#editItemModal').on('hidden.bs.modal', function() {
                    $(this).remove();
                });
            },
            error: function(xhr) {
                Swal.fire(
                    'Error!',
                    'Failed to load item data.',
                    'error'
                );
            }
        });
    });

    // Bulk Upload functionality
    $('#uploadBtn').click(function() {
        let formData = new FormData($('#bulkUploadForm')[0]);

        Swal.fire({
            title: 'Processing Upload',
            html: 'Please wait while we process your file...',
            allowOutsideClick: false,
            didOpen: () => {
                Swal.showLoading();
            }
        });

        $.ajax({
            url: "{{ route('items.bulk-upload') }}",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            success: function(response) {
                Swal.fire({
                    icon: 'success',
                    title: 'Success!',
                    html: response.message + '<br>' +
                          'Success: ' + response.success_count + '<br>' +
                          'Failed: ' + response.failure_count,
                }).then(() => {
                    $('#bulkUploadModal').modal('hide');
                    table.ajax.reload();
                    $('#bulkUploadForm')[0].reset();
                });
            },
            error: function(xhr) {
                let errorMessage = xhr.responseJSON?.message || 'An error occurred during upload.';
                Swal.fire({
                    icon: 'error',
                    title: 'Upload Failed',
                    text: errorMessage,
                });
            }
        });
    });

    // Reload the table after modal is closed
    $(document).on('hidden.bs.modal', '#editItemModal', function() {
        table.ajax.reload(null, false);
    });
});
</script>

@endsection
